version: '3.8'

services:
  postgres:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - '5432:5432'
    networks:
      - prod-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    restart: always
    ports:
      - '6379:6379'
    networks:
      - prod-network
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}

  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - '2181:2181'
    environment:
      ALLOW_ANONYMOUS_LOGIN: ${ALLOW_ANONYMOUS_LOGIN}
    networks:
      - prod-network
    volumes:
      - zookeeper_data:/bitnami

  kafka:
    image: bitnami/kafka:3.9
    restart: always
    ports:
      - '9092:9092'
      - '9093:9093'
    environment:
      KAFKA_BROKER_ID: ${KAFKA_BROKER_ID}
      KAFKA_CFG_KRAFT_MODE: ${KAFKA_CFG_KRAFT_MODE}
      KAFKA_CFG_ZOOKEEPER_CONNECT: ${KAFKA_CFG_ZOOKEEPER_CONNECT}
      KAFKA_CFG_ADVERTISED_LISTENERS: ${KAFKA_CFG_ADVERTISED_LISTENERS}
      KAFKA_CFG_LISTENERS: ${KAFKA_CFG_LISTENERS}
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: ${KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP}
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: ${KAFKA_CFG_INTER_BROKER_LISTENER_NAME}
      ALLOW_PLAINTEXT_LISTENER: ${ALLOW_PLAINTEXT_LISTENER}
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: ${KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE}
    depends_on:
      - zookeeper
    networks:
      - prod-network
    volumes:
      - kafka_data:/bitnami
    healthcheck:
      test:
        ['CMD-SHELL', 'kafka-broker-api-versions.sh --bootstrap-server localhost:9092 || exit 1']
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s

  auth-service:
    build:
      context: .
      dockerfile: ./apps/auth-service/Dockerfile
      target: production
    # Remove port mapping for production - only nginx should be exposed
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
    environment:
      PORT: ${AUTH_SERVICE_PORT}
      JWT_SECRET: ${JWT_SECRET}
      DB_HOST: ${AUTH_DB_HOST}
      DB_PORT: ${AUTH_DB_PORT}
      DB_USERNAME: ${AUTH_DB_USERNAME}
      DB_PASSWORD: ${AUTH_DB_PASSWORD}
      DB_NAME: ${AUTH_DB_NAME}
      KAFKA_BROKERS: ${KAFKA_BROKERS}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      NODE_ENV: ${NODE_ENV}
    networks:
      - prod-network
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'curl -f http://localhost:${AUTH_SERVICE_PORT}/health || exit 1']
      interval: 30s
      timeout: 10s
      retries: 3

  users-service:
    build:
      context: .
      dockerfile: ./apps/users-service/Dockerfile
      target: production
    # Remove port mapping for production - only nginx should be exposed
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
    environment:
      PORT: ${USERS_SERVICE_PORT}
      JWT_SECRET: ${JWT_SECRET}
      DB_HOST: ${USERS_DB_HOST}
      DB_PORT: ${USERS_DB_PORT}
      DB_USERNAME: ${USERS_DB_USERNAME}
      DB_PASSWORD: ${USERS_DB_PASSWORD}
      DB_NAME: ${USERS_DB_NAME}
      KAFKA_BROKERS: ${KAFKA_BROKERS}
      NODE_ENV: ${NODE_ENV}
    networks:
      - prod-network
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'curl -f http://localhost:${USERS_SERVICE_PORT}/health || exit 1']
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:latest
    container_name: nginx-gateway-prod
    ports:
      - '${NGINX_PORT}:80'
      - '443:443'
    volumes:
      - ./gateway/default.conf:/etc/nginx/conf.d/default.conf
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf
      # SSL certificates (uncomment when ready)
      # - ./ssl:/etc/nginx/ssl
    depends_on:
      - auth-service
      - users-service
    networks:
      - prod-network
    restart: unless-stopped

volumes:
  pgdata:
  redis_data:
  zookeeper_data:
  kafka_data:

networks:
  prod-network:
    driver: bridge
